In [1]:
import numpy as np

X = np.array([[1,2]])

print("Input:")
print(X)

print("Shape:",X.shape)

Input:
[[1 2]]
Shape: (1, 2)


In [2]:
W1 = np.array([
    [0.1,0.2],
    [0.3,0.4]
])

b1 = np.array([[0.1,0.1]])

print("W1 Shape:",W1.shape)
print("b1 Shape:",b1.shape)

W1 Shape: (2, 2)
b1 Shape: (1, 2)


In [4]:
Z1 = np.dot(X,W1) + b1

print("Z1:")
print(Z1)  # Pre activsation output

print("Shape:",Z1.shape)

Z1:
[[0.8 1.1]]
Shape: (1, 2)


In [5]:
# Activation function

def sigmoid(x):
    return 1/(1+np.exp(-x))

In [8]:
A1 = sigmoid(Z1)

print("A1:")
print(A1)
print("Shape:",A1.shape)

# Use of activation function is that it can learn curves, shapes, images in data apart from linear patterns

A1:
[[0.68997448 0.75026011]]
Shape: (1, 2)


In [10]:
W2 = np.array([
    [0.5],
    [0.6]
])

b2 = np.array([[0.1]])

In [12]:
Z2 = np.dot(A1,W2)+b2

print(Z2)
print("Shape:",Z2.shape)

[[0.8951433]]
Shape: (1, 1)


In [13]:
A2 = sigmoid(Z2)

print(A2)

[[0.70995043]]
